### ISSUE TITLE
Installed trial is not working

### ISSUE THREAD

**Issue by nschroeer** [MaxLaumeister/hideyt-issues#1]
Hello,
I installed the 14 day free trial in my WordPress plugins, and the embedded videos are still showing suggested video thumbnails and the end. Am I missing a step?
- Nicole

**Comment by MaxLaumeister** [comment]
Hi Nicole! Thanks for bringing this to my attention!

If it's not working at this point, it might be a compatibility issue, since WordPress sites vary so much. When we find something like this, we like to look at the site manually to see if we can issue an update to the plug-in to improve compatibility.

At your convenience, could I ask you to supply a page with an embedded video that demonstrates the issue? If you would rather not post it publicly, you can email it to support@hideyt.com. Thanks!
